db:
  name: postgres
  password: 12345
  ip: 127.0.0.1
  port: 5432
  database: postgres
server:
  port: 8010
log:
  stdout:
    enable: true
    level: 5
  file:
    enable: true
    path: "./log/app.log"
    level: 4
  kafka:
    enable: false
    topic: "spb"
    kafka_servers:
      - "kafka-1.spb.com:9092"
    level: 3
email:
  smtpServer: "smtp.gmail.com"
  smtpPort: 465
  smtpUsername: "callmelwb@gmail.com"
  smtpPassword: "kafywgqmcsriiljl"
Redis:
  addr: "localhost:6379"
  password: ""
  db: 0
Endpoint:
  Trx: "grpc.trongrid.io:50051" #"grpc.shasta.trongrid.io:50051"
Schedule:
  time : "12:00"
